# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixProd <- function(A, B) {
    .Call(`_toxassay_matrixProd`, A, B)
}

get_pi <- function(X, Y) {
    .Call(`_toxassay_get_pi`, X, Y)
}

get_psi <- function(X, Y) {
    .Call(`_toxassay_get_psi`, X, Y)
}

